/*
 * generated by Xtext
 */
package org.eclipse.emf.mwe2.language;

import org.eclipse.emf.mwe2.language.scoping.JvmTypesAwareGlobalScopeProvider;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Mwe2RuntimeModule extends org.eclipse.emf.mwe2.language.AbstractMwe2RuntimeModule {
	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return JvmTypesAwareGlobalScopeProvider.class;
	}
}
