/*
 * generated by Xtext
 */
package org.eclipse.emf.mwe.properties;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PropertiesUiModule extends org.eclipse.emf.mwe.properties.AbstractMWEPropertiesUiModule {

}
