/*
 * generated by Xtext
 */
package org.eclipse.emf.mwe2.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.emf.mwe2.language.ui.internal.Mwe2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Mwe2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Mwe2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Mwe2Activator.getInstance().getInjector(Mwe2Activator.ORG_ECLIPSE_EMF_MWE2_LANGUAGE_MWE2);
	}
	
}
