/**
 * <copyright>
 * </copyright>
 *
 * $Id: ConcatValidator.java,v 1.1 2009/02/15 19:18:45 bhunt Exp $
 */
package org.eclipse.emf.mwe.ewm.examples.tutorial.validation;

import org.eclipse.emf.mwe.ewm.workflow.WorkflowParameter;

/**
 * A sample validator interface for {@link org.eclipse.emf.mwe.ewm.examples.tutorial.Concat}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConcatValidator
{
	boolean validate();

	boolean validateInputMessage(WorkflowParameter value);
	boolean validateInputAppendMessage(WorkflowParameter value);
	boolean validateOutputMessage(WorkflowParameter value);
}
