/**
 * <copyright>
 * </copyright>
 *
 * $Id: WorkflowPredicateORValidator.java,v 1.1 2009/05/14 04:12:29 bhunt Exp $
 */
package org.eclipse.emf.mwe.ewm.workflow.orchestration.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.mwe.ewm.workflow.orchestration.WorkflowExecutionPredicate;


/**
 * A sample validator interface for {@link org.eclipse.emf.mwe.ewm.workflow.orchestration.WorkflowPredicateOR}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowPredicateORValidator
{
	boolean validate();

	boolean validateConditions(EList<WorkflowExecutionPredicate> value);

}
