/*
* generated by Xtext
*/

package org.eclipse.emf.mwe.di.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;

import org.eclipse.xtext.service.GrammarProvider;

import org.eclipse.xtext.builtin.XtextBuiltinGrammarAccess;

@Singleton
public class MWEGrammarAccess implements IGrammarAccess {
	
	
	public class FileElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "File");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group c0Group = (Group)cGroup.eContents().get(0);
		private final Assignment c00AssignmentImports = (Assignment)c0Group.eContents().get(0);
		private final RuleCall c000ParserRuleCallImport = (RuleCall)c00AssignmentImports.eContents().get(0);
		private final Assignment c01AssignmentProperties = (Assignment)c0Group.eContents().get(1);
		private final RuleCall c010ParserRuleCallProperty = (RuleCall)c01AssignmentProperties.eContents().get(0);
		private final Assignment c1AssignmentValue = (Assignment)cGroup.eContents().get(1);
		private final RuleCall c10ParserRuleCallComplexValue = (RuleCall)c1AssignmentValue.eContents().get(0);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Group eleGroup() { return cGroup; }

		// not supported
		public Group ele0Group() { return c0Group; }

		// not supported
		public Assignment ele00AssignmentImports() { return c00AssignmentImports; }

		// not supported
		public RuleCall ele000ParserRuleCallImport() { return c000ParserRuleCallImport; }

		// not supported
		public Assignment ele01AssignmentProperties() { return c01AssignmentProperties; }

		// not supported
		public RuleCall ele010ParserRuleCallProperty() { return c010ParserRuleCallProperty; }

		// not supported
		public Assignment ele1AssignmentValue() { return c1AssignmentValue; }

		// not supported
		public RuleCall ele10ParserRuleCallComplexValue() { return c10ParserRuleCallComplexValue; }
	}

	public class ImportElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Import");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall c0ParserRuleCallJavaImport = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall c1ParserRuleCallGenericImport = (RuleCall)cAlternatives.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Alternatives eleAlternatives() { return cAlternatives; }

		// not supported
		public RuleCall ele0ParserRuleCallJavaImport() { return c0ParserRuleCallJavaImport; }

		// not supported
		public RuleCall ele1ParserRuleCallGenericImport() { return c1ParserRuleCallGenericImport; }
	}

	public class JavaImportElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JavaImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group c0Group = (Group)cGroup.eContents().get(0);
		private final Group c00Group = (Group)c0Group.eContents().get(0);
		private final Keyword c000KeywordImport = (Keyword)c00Group.eContents().get(0);
		private final Assignment c001AssignmentJavaImport = (Assignment)c00Group.eContents().get(1);
		private final RuleCall c0010ParserRuleCallQualifiedName = (RuleCall)c001AssignmentJavaImport.eContents().get(0);
		private final Group c01Group = (Group)c0Group.eContents().get(1);
		private final Keyword c010KeywordFullStop = (Keyword)c01Group.eContents().get(0);
		private final Assignment c011AssignmentWildcard = (Assignment)c01Group.eContents().get(1);
		private final Keyword c0110KeywordAsterisk = (Keyword)c011AssignmentWildcard.eContents().get(0);
		private final Keyword c1KeywordSemicolon = (Keyword)cGroup.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Group eleGroup() { return cGroup; }

		// not supported
		public Group ele0Group() { return c0Group; }

		// not supported
		public Group ele00Group() { return c00Group; }

		// not supported
		public Keyword ele000KeywordImport() { return c000KeywordImport; }

		// not supported
		public Assignment ele001AssignmentJavaImport() { return c001AssignmentJavaImport; }

		// not supported
		public RuleCall ele0010ParserRuleCallQualifiedName() { return c0010ParserRuleCallQualifiedName; }

		// not supported
		public Group ele01Group() { return c01Group; }

		// not supported
		public Keyword ele010KeywordFullStop() { return c010KeywordFullStop; }

		// not supported
		public Assignment ele011AssignmentWildcard() { return c011AssignmentWildcard; }

		// not supported
		public Keyword ele0110KeywordAsterisk() { return c0110KeywordAsterisk; }

		// not supported
		public Keyword ele1KeywordSemicolon() { return c1KeywordSemicolon; }
	}

	public class GenericImportElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GenericImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group c0Group = (Group)cGroup.eContents().get(0);
		private final Keyword c00KeywordImport = (Keyword)c0Group.eContents().get(0);
		private final Assignment c01AssignmentValue = (Assignment)c0Group.eContents().get(1);
		private final RuleCall c010LexerRuleCallSTRING = (RuleCall)c01AssignmentValue.eContents().get(0);
		private final Keyword c1KeywordSemicolon = (Keyword)cGroup.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Group eleGroup() { return cGroup; }

		// not supported
		public Group ele0Group() { return c0Group; }

		// not supported
		public Keyword ele00KeywordImport() { return c00KeywordImport; }

		// not supported
		public Assignment ele01AssignmentValue() { return c01AssignmentValue; }

		// not supported
		public RuleCall ele010LexerRuleCallSTRING() { return c010LexerRuleCallSTRING; }

		// not supported
		public Keyword ele1KeywordSemicolon() { return c1KeywordSemicolon; }
	}

	public class PropertyElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall c0ParserRuleCallLocalVariable = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall c1ParserRuleCallPropertiesFileImport = (RuleCall)cAlternatives.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Alternatives eleAlternatives() { return cAlternatives; }

		// not supported
		public RuleCall ele0ParserRuleCallLocalVariable() { return c0ParserRuleCallLocalVariable; }

		// not supported
		public RuleCall ele1ParserRuleCallPropertiesFileImport() { return c1ParserRuleCallPropertiesFileImport; }
	}

	public class LocalVariableElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LocalVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group c0Group = (Group)cGroup.eContents().get(0);
		private final Group c00Group = (Group)c0Group.eContents().get(0);
		private final Keyword c000KeywordVar = (Keyword)c00Group.eContents().get(0);
		private final Assignment c001AssignmentName = (Assignment)c00Group.eContents().get(1);
		private final RuleCall c0010LexerRuleCallID = (RuleCall)c001AssignmentName.eContents().get(0);
		private final Group c01Group = (Group)c0Group.eContents().get(1);
		private final Keyword c010KeywordEqualsSign = (Keyword)c01Group.eContents().get(0);
		private final Assignment c011AssignmentValue = (Assignment)c01Group.eContents().get(1);
		private final RuleCall c0110ParserRuleCallValue = (RuleCall)c011AssignmentValue.eContents().get(0);
		private final Keyword c1KeywordSemicolon = (Keyword)cGroup.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Group eleGroup() { return cGroup; }

		// not supported
		public Group ele0Group() { return c0Group; }

		// not supported
		public Group ele00Group() { return c00Group; }

		// not supported
		public Keyword ele000KeywordVar() { return c000KeywordVar; }

		// not supported
		public Assignment ele001AssignmentName() { return c001AssignmentName; }

		// not supported
		public RuleCall ele0010LexerRuleCallID() { return c0010LexerRuleCallID; }

		// not supported
		public Group ele01Group() { return c01Group; }

		// not supported
		public Keyword ele010KeywordEqualsSign() { return c010KeywordEqualsSign; }

		// not supported
		public Assignment ele011AssignmentValue() { return c011AssignmentValue; }

		// not supported
		public RuleCall ele0110ParserRuleCallValue() { return c0110ParserRuleCallValue; }

		// not supported
		public Keyword ele1KeywordSemicolon() { return c1KeywordSemicolon; }
	}

	public class PropertiesFileImportElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PropertiesFileImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group c0Group = (Group)cGroup.eContents().get(0);
		private final Group c00Group = (Group)c0Group.eContents().get(0);
		private final Keyword c000KeywordVar = (Keyword)c00Group.eContents().get(0);
		private final Keyword c001KeywordFile = (Keyword)c00Group.eContents().get(1);
		private final Assignment c01AssignmentFile = (Assignment)c0Group.eContents().get(1);
		private final RuleCall c010LexerRuleCallSTRING = (RuleCall)c01AssignmentFile.eContents().get(0);
		private final Keyword c1KeywordSemicolon = (Keyword)cGroup.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Group eleGroup() { return cGroup; }

		// not supported
		public Group ele0Group() { return c0Group; }

		// not supported
		public Group ele00Group() { return c00Group; }

		// not supported
		public Keyword ele000KeywordVar() { return c000KeywordVar; }

		// not supported
		public Keyword ele001KeywordFile() { return c001KeywordFile; }

		// not supported
		public Assignment ele01AssignmentFile() { return c01AssignmentFile; }

		// not supported
		public RuleCall ele010LexerRuleCallSTRING() { return c010LexerRuleCallSTRING; }

		// not supported
		public Keyword ele1KeywordSemicolon() { return c1KeywordSemicolon; }
	}

	public class ValueElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Alternatives c0Alternatives = (Alternatives)cAlternatives.eContents().get(0);
		private final Alternatives c00Alternatives = (Alternatives)c0Alternatives.eContents().get(0);
		private final RuleCall c000ParserRuleCallSimpleValue = (RuleCall)c00Alternatives.eContents().get(0);
		private final RuleCall c001ParserRuleCallComplexValue = (RuleCall)c00Alternatives.eContents().get(1);
		private final RuleCall c01ParserRuleCallIdRef = (RuleCall)c0Alternatives.eContents().get(1);
		private final RuleCall c1ParserRuleCallWorkflowRef = (RuleCall)cAlternatives.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Alternatives eleAlternatives() { return cAlternatives; }

		// not supported
		public Alternatives ele0Alternatives() { return c0Alternatives; }

		// not supported
		public Alternatives ele00Alternatives() { return c00Alternatives; }

		// not supported
		public RuleCall ele000ParserRuleCallSimpleValue() { return c000ParserRuleCallSimpleValue; }

		// not supported
		public RuleCall ele001ParserRuleCallComplexValue() { return c001ParserRuleCallComplexValue; }

		// not supported
		public RuleCall ele01ParserRuleCallIdRef() { return c01ParserRuleCallIdRef; }

		// not supported
		public RuleCall ele1ParserRuleCallWorkflowRef() { return c1ParserRuleCallWorkflowRef; }
	}

	public class SimpleValueElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SimpleValue");
		private final Assignment cAssignmentValue = (Assignment)rule.eContents().get(1);
		private final RuleCall c0LexerRuleCallSTRING = (RuleCall)cAssignmentValue.eContents().get(0);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Assignment eleAssignmentValue() { return cAssignmentValue; }

		// not supported
		public RuleCall ele0LexerRuleCallSTRING() { return c0LexerRuleCallSTRING; }
	}

	public class AssignableElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Assignable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall c0ParserRuleCallComplexValue = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall c1ParserRuleCallWorkflowRef = (RuleCall)cAlternatives.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Alternatives eleAlternatives() { return cAlternatives; }

		// not supported
		public RuleCall ele0ParserRuleCallComplexValue() { return c0ParserRuleCallComplexValue; }

		// not supported
		public RuleCall ele1ParserRuleCallWorkflowRef() { return c1ParserRuleCallWorkflowRef; }
	}

	public class ComplexValueElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ComplexValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group c0Group = (Group)cGroup.eContents().get(0);
		private final Group c00Group = (Group)c0Group.eContents().get(0);
		private final Group c000Group = (Group)c00Group.eContents().get(0);
		private final Assignment c0000AssignmentClassName = (Assignment)c000Group.eContents().get(0);
		private final RuleCall c00000ParserRuleCallQualifiedName = (RuleCall)c0000AssignmentClassName.eContents().get(0);
		private final Group c0001Group = (Group)c000Group.eContents().get(1);
		private final Keyword c00010KeywordColon = (Keyword)c0001Group.eContents().get(0);
		private final Assignment c00011AssignmentId = (Assignment)c0001Group.eContents().get(1);
		private final RuleCall c000110LexerRuleCallID = (RuleCall)c00011AssignmentId.eContents().get(0);
		private final Assignment c001AssignmentFooBar = (Assignment)c00Group.eContents().get(1);
		private final Keyword c0010KeywordLeftCurlyBracket = (Keyword)c001AssignmentFooBar.eContents().get(0);
		private final Assignment c01AssignmentAssignments = (Assignment)c0Group.eContents().get(1);
		private final RuleCall c010ParserRuleCallAssignment = (RuleCall)c01AssignmentAssignments.eContents().get(0);
		private final Keyword c1KeywordRightCurlyBracket = (Keyword)cGroup.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Group eleGroup() { return cGroup; }

		// not supported
		public Group ele0Group() { return c0Group; }

		// not supported
		public Group ele00Group() { return c00Group; }

		// not supported
		public Group ele000Group() { return c000Group; }

		// not supported
		public Assignment ele0000AssignmentClassName() { return c0000AssignmentClassName; }

		// not supported
		public RuleCall ele00000ParserRuleCallQualifiedName() { return c00000ParserRuleCallQualifiedName; }

		// not supported
		public Group ele0001Group() { return c0001Group; }

		// not supported
		public Keyword ele00010KeywordColon() { return c00010KeywordColon; }

		// not supported
		public Assignment ele00011AssignmentId() { return c00011AssignmentId; }

		// not supported
		public RuleCall ele000110LexerRuleCallID() { return c000110LexerRuleCallID; }

		// not supported
		public Assignment ele001AssignmentFooBar() { return c001AssignmentFooBar; }

		// not supported
		public Keyword ele0010KeywordLeftCurlyBracket() { return c0010KeywordLeftCurlyBracket; }

		// not supported
		public Assignment ele01AssignmentAssignments() { return c01AssignmentAssignments; }

		// not supported
		public RuleCall ele010ParserRuleCallAssignment() { return c010ParserRuleCallAssignment; }

		// not supported
		public Keyword ele1KeywordRightCurlyBracket() { return c1KeywordRightCurlyBracket; }
	}

	public class WorkflowRefElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WorkflowRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group c0Group = (Group)cGroup.eContents().get(0);
		private final Group c00Group = (Group)c0Group.eContents().get(0);
		private final Group c000Group = (Group)c00Group.eContents().get(0);
		private final Keyword c0000KeywordFile = (Keyword)c000Group.eContents().get(0);
		private final Assignment c0001AssignmentUri = (Assignment)c000Group.eContents().get(1);
		private final RuleCall c00010LexerRuleCallSTRING = (RuleCall)c0001AssignmentUri.eContents().get(0);
		private final Keyword c001KeywordLeftCurlyBracket = (Keyword)c00Group.eContents().get(1);
		private final Assignment c01AssignmentAssignments = (Assignment)c0Group.eContents().get(1);
		private final RuleCall c010ParserRuleCallAssignment = (RuleCall)c01AssignmentAssignments.eContents().get(0);
		private final Keyword c1KeywordRightCurlyBracket = (Keyword)cGroup.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Group eleGroup() { return cGroup; }

		// not supported
		public Group ele0Group() { return c0Group; }

		// not supported
		public Group ele00Group() { return c00Group; }

		// not supported
		public Group ele000Group() { return c000Group; }

		// not supported
		public Keyword ele0000KeywordFile() { return c0000KeywordFile; }

		// not supported
		public Assignment ele0001AssignmentUri() { return c0001AssignmentUri; }

		// not supported
		public RuleCall ele00010LexerRuleCallSTRING() { return c00010LexerRuleCallSTRING; }

		// not supported
		public Keyword ele001KeywordLeftCurlyBracket() { return c001KeywordLeftCurlyBracket; }

		// not supported
		public Assignment ele01AssignmentAssignments() { return c01AssignmentAssignments; }

		// not supported
		public RuleCall ele010ParserRuleCallAssignment() { return c010ParserRuleCallAssignment; }

		// not supported
		public Keyword ele1KeywordRightCurlyBracket() { return c1KeywordRightCurlyBracket; }
	}

	public class IdRefElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IdRef");
		private final Assignment cAssignmentId = (Assignment)rule.eContents().get(1);
		private final RuleCall c0LexerRuleCallID = (RuleCall)cAssignmentId.eContents().get(0);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Assignment eleAssignmentId() { return cAssignmentId; }

		// not supported
		public RuleCall ele0LexerRuleCallID() { return c0LexerRuleCallID; }
	}

	public class AssignmentElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Assignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group c0Group = (Group)cGroup.eContents().get(0);
		private final Group c00Group = (Group)c0Group.eContents().get(0);
		private final Assignment c000AssignmentFeature = (Assignment)c00Group.eContents().get(0);
		private final RuleCall c0000LexerRuleCallID = (RuleCall)c000AssignmentFeature.eContents().get(0);
		private final Assignment c001AssignmentOperator = (Assignment)c00Group.eContents().get(1);
		private final Alternatives c0010Alternatives = (Alternatives)c001AssignmentOperator.eContents().get(0);
		private final Keyword c00100KeywordEqualsSign = (Keyword)c0010Alternatives.eContents().get(0);
		private final Keyword c00101KeywordPlusSignEqualsSign = (Keyword)c0010Alternatives.eContents().get(1);
		private final Assignment c01AssignmentValue = (Assignment)c0Group.eContents().get(1);
		private final RuleCall c010ParserRuleCallValue = (RuleCall)c01AssignmentValue.eContents().get(0);
		private final Keyword c1KeywordSemicolon = (Keyword)cGroup.eContents().get(1);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Group eleGroup() { return cGroup; }

		// not supported
		public Group ele0Group() { return c0Group; }

		// not supported
		public Group ele00Group() { return c00Group; }

		// not supported
		public Assignment ele000AssignmentFeature() { return c000AssignmentFeature; }

		// not supported
		public RuleCall ele0000LexerRuleCallID() { return c0000LexerRuleCallID; }

		// not supported
		public Assignment ele001AssignmentOperator() { return c001AssignmentOperator; }

		// not supported
		public Alternatives ele0010Alternatives() { return c0010Alternatives; }

		// not supported
		public Keyword ele00100KeywordEqualsSign() { return c00100KeywordEqualsSign; }

		// not supported
		public Keyword ele00101KeywordPlusSignEqualsSign() { return c00101KeywordPlusSignEqualsSign; }

		// not supported
		public Assignment ele01AssignmentValue() { return c01AssignmentValue; }

		// not supported
		public RuleCall ele010ParserRuleCallValue() { return c010ParserRuleCallValue; }

		// not supported
		public Keyword ele1KeywordSemicolon() { return c1KeywordSemicolon; }
	}

	public class QualifiedNameElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment c0AssignmentParts = (Assignment)cGroup.eContents().get(0);
		private final RuleCall c00LexerRuleCallID = (RuleCall)c0AssignmentParts.eContents().get(0);
		private final Group c1Group = (Group)cGroup.eContents().get(1);
		private final Assignment c10AssignmentParts = (Assignment)c1Group.eContents().get(0);
		private final Keyword c100KeywordFullStop = (Keyword)c10AssignmentParts.eContents().get(0);
		private final Assignment c11AssignmentParts = (Assignment)c1Group.eContents().get(1);
		private final RuleCall c110LexerRuleCallID = (RuleCall)c11AssignmentParts.eContents().get(0);
		
		// not supported
		public ParserRule getRule() { return rule; }

		// not supported
		public Group eleGroup() { return cGroup; }

		// not supported
		public Assignment ele0AssignmentParts() { return c0AssignmentParts; }

		// not supported
		public RuleCall ele00LexerRuleCallID() { return c00LexerRuleCallID; }

		// not supported
		public Group ele1Group() { return c1Group; }

		// not supported
		public Assignment ele10AssignmentParts() { return c10AssignmentParts; }

		// not supported
		public Keyword ele100KeywordFullStop() { return c100KeywordFullStop; }

		// not supported
		public Assignment ele11AssignmentParts() { return c11AssignmentParts; }

		// not supported
		public RuleCall ele110LexerRuleCallID() { return c110LexerRuleCallID; }
	}
	
	private FileElements pFile;
	private ImportElements pImport;
	private JavaImportElements pJavaImport;
	private GenericImportElements pGenericImport;
	private PropertyElements pProperty;
	private LocalVariableElements pLocalVariable;
	private PropertiesFileImportElements pPropertiesFileImport;
	private ValueElements pValue;
	private SimpleValueElements pSimpleValue;
	private AssignableElements pAssignable;
	private ComplexValueElements pComplexValue;
	private WorkflowRefElements pWorkflowRef;
	private IdRefElements pIdRef;
	private AssignmentElements pAssignment;
	private QualifiedNameElements pQualifiedName;
	
	private final GrammarProvider grammarProvider;

	private XtextBuiltinGrammarAccess superGrammarAccess;

	@Inject
	public MWEGrammarAccess(GrammarProvider grammarProvider, XtextBuiltinGrammarAccess superGrammarAccess) {
		this.grammarProvider = grammarProvider;
		this.superGrammarAccess = superGrammarAccess;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public XtextBuiltinGrammarAccess getSuperGrammarAccess() {
		return superGrammarAccess;
	}

	
	// not supported
	public FileElements prFile() {
		return (pFile != null) ? pFile : (pFile = new FileElements());
	} 

	// not supported
	public ImportElements prImport() {
		return (pImport != null) ? pImport : (pImport = new ImportElements());
	} 

	// not supported
	public JavaImportElements prJavaImport() {
		return (pJavaImport != null) ? pJavaImport : (pJavaImport = new JavaImportElements());
	} 

	// not supported
	public GenericImportElements prGenericImport() {
		return (pGenericImport != null) ? pGenericImport : (pGenericImport = new GenericImportElements());
	} 

	// not supported
	public PropertyElements prProperty() {
		return (pProperty != null) ? pProperty : (pProperty = new PropertyElements());
	} 

	// not supported
	public LocalVariableElements prLocalVariable() {
		return (pLocalVariable != null) ? pLocalVariable : (pLocalVariable = new LocalVariableElements());
	} 

	// not supported
	public PropertiesFileImportElements prPropertiesFileImport() {
		return (pPropertiesFileImport != null) ? pPropertiesFileImport : (pPropertiesFileImport = new PropertiesFileImportElements());
	} 

	// not supported
	public ValueElements prValue() {
		return (pValue != null) ? pValue : (pValue = new ValueElements());
	} 

	// not supported
	public SimpleValueElements prSimpleValue() {
		return (pSimpleValue != null) ? pSimpleValue : (pSimpleValue = new SimpleValueElements());
	} 

	// not supported
	public AssignableElements prAssignable() {
		return (pAssignable != null) ? pAssignable : (pAssignable = new AssignableElements());
	} 

	// not supported
	public ComplexValueElements prComplexValue() {
		return (pComplexValue != null) ? pComplexValue : (pComplexValue = new ComplexValueElements());
	} 

	// not supported
	public WorkflowRefElements prWorkflowRef() {
		return (pWorkflowRef != null) ? pWorkflowRef : (pWorkflowRef = new WorkflowRefElements());
	} 

	// not supported
	public IdRefElements prIdRef() {
		return (pIdRef != null) ? pIdRef : (pIdRef = new IdRefElements());
	} 

	// not supported
	public AssignmentElements prAssignment() {
		return (pAssignment != null) ? pAssignment : (pAssignment = new AssignmentElements());
	} 

	// not supported
	public QualifiedNameElements prQualifiedName() {
		return (pQualifiedName != null) ? pQualifiedName : (pQualifiedName = new QualifiedNameElements());
	} 

	// not supported
	public LexerRule lrID() {
		return superGrammarAccess.lrID();
	} 

	// not supported
	public LexerRule lrINT() {
		return superGrammarAccess.lrINT();
	} 

	// not supported
	public LexerRule lrSTRING() {
		return superGrammarAccess.lrSTRING();
	} 

	// not supported
	public LexerRule lrML_COMMENT() {
		return superGrammarAccess.lrML_COMMENT();
	} 

	// not supported
	public LexerRule lrSL_COMMENT() {
		return superGrammarAccess.lrSL_COMMENT();
	} 

	// not supported
	public LexerRule lrWS() {
		return superGrammarAccess.lrWS();
	} 

	// not supported
	public LexerRule lrANY_OTHER() {
		return superGrammarAccess.lrANY_OTHER();
	} 
}
