/*
* generated by Xtext
*/
package org.eclipse.emf.mwe.di.parser.packrat.consumers;

import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.AbstractRule;

import org.eclipse.xtext.parser.packrat.IMarkerFactory.IMarker;
import org.eclipse.xtext.parser.packrat.consumers.ITerminalConsumer;
import org.eclipse.xtext.parser.packrat.consumers.INonTerminalConsumer;
import org.eclipse.xtext.parser.packrat.consumers.NonTerminalConsumer;
import org.eclipse.xtext.parser.packrat.consumers.INonTerminalConsumerConfiguration;
import org.eclipse.xtext.parser.packrat.consumers.ConsumeResult;
import org.eclipse.xtext.parser.packrat.matching.ICharacterClass;
import org.eclipse.xtext.parser.packrat.matching.ISequenceMatcher;

import org.eclipse.emf.mwe.di.services.MWEGrammarAccess.ImportElements;

import org.eclipse.emf.mwe.di.parser.packrat.consumers.MWEGenericImportConsumer;
import org.eclipse.emf.mwe.di.parser.packrat.consumers.MWEJavaImportConsumer;

@SuppressWarnings("unused")
public final class MWEImportConsumer extends NonTerminalConsumer {

	private ImportElements rule;
	
	private INonTerminalConsumer genericImportConsumer;
	private INonTerminalConsumer javaImportConsumer;

	public MWEImportConsumer(INonTerminalConsumerConfiguration configuration, ITerminalConsumer[] hiddenTokens) {
		super(configuration, hiddenTokens);
	}
	
	@Override
	protected int doConsume(int entryPoint) throws Exception {
		return consumeAlternatives$1(entryPoint);
	}

	protected int consumeAlternatives$1(int entryPoint) throws Exception {
		AlternativesResult result = createAlternativesResult();
		switch(entryPoint) {
			case -1: // use fall through semantics of switch case
				result.reset();
			case 0:
				result.nextAlternative();
				if (result.isAlternativeDone(consumeRuleCall$2(nextEntryPoint()))) { 
					return result.getResult(); 
				}
			case 1:
				result.nextAlternative();
				if (result.isAlternativeDone(consumeRuleCall$3(nextEntryPoint()))) { 
					return result.getResult(); 
				}
		}
		return result.getResult();
	}

	protected int consumeRuleCall$2(int entryPoint) throws Exception {
		return consumeNonTerminal(javaImportConsumer, null, false, false, false, getRule().ele0ParserRuleCallJavaImport());
	}

	protected int consumeRuleCall$3(int entryPoint) throws Exception {
		return consumeNonTerminal(genericImportConsumer, null, false, false, false, getRule().ele1ParserRuleCallGenericImport());
	}

	public ImportElements getRule() {
		return rule;
	}
	
	public void setRule(ImportElements rule) {
		this.rule = rule;
	}
	
	@Override
	protected AbstractRule getGrammarElement() {
		return getRule().getRule();
	}

	@Override
	protected EClassifier getDefaultType() {
		return getGrammarElement().getType().getType();
	}
	
	public void setGenericImportConsumer(INonTerminalConsumer genericImportConsumer) {
		this.genericImportConsumer = genericImportConsumer;
	}
	
	public void setJavaImportConsumer(INonTerminalConsumer javaImportConsumer) {
		this.javaImportConsumer = javaImportConsumer;
	}
	
}
