
/*
 * generated by Xtext
 */
 
package org.eclipse.emf.mwe.concept;

import org.eclipse.xtext.ui.core.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class MWEConceptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.emf.mwe.concept.internal.MWEConceptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipse.emf.mwe.concept.internal.MWEConceptActivator.getInstance().getInjector("org.eclipse.emf.mwe.concept.MWEConcept");
	}
	
}
