/**
 * <copyright>
 * </copyright>
 *
 * $Id: WorkflowSkippedStateValidator.java,v 1.1 2009/05/14 04:12:31 bhunt Exp $
 */
package org.eclipse.emf.mwe.ewm.workflow.runtime.state.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.mwe.ewm.workflow.runtime.state.WorkflowSkippedState}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowSkippedStateValidator
{
	boolean validate();

}
