<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="workflow"
    nsURI="http://www.eclipse.org/emf/mwe/ewm/workflow" nsPrefix="org.eclipse.emf.mwe.ewm.workflow">
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowComponent" abstract="true">
    <eOperations name="start">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
    </eOperations>
    <eOperations name="run" eType="#//runtime/state/WorkflowState" eExceptions="#//runtime/WorkflowRuntimeException">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentOrchestrationStrategy"
        eType="#//orchestration/WorkflowComponentOrchestrationStrategy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowCompositeComponent" eSuperTypes="#//WorkflowComponent">
    <eOperations name="run" eType="#//runtime/state/WorkflowState" eExceptions="#//runtime/WorkflowRuntimeException">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//WorkflowComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//WorkflowParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeOrchestrationStrategy"
        lowerBound="1" eType="#//orchestration/WorkflowCompositeOrchestrationStrategy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//WorkflowParameterConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateResolutionStrategy"
        lowerBound="1" eType="#//runtime/WorkflowStateResolutionStrategy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowUnitOfWork" abstract="true"
      eSuperTypes="#//WorkflowComponent">
    <eOperations name="run" eType="#//runtime/state/WorkflowState" eExceptions="#//runtime/WorkflowRuntimeException">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowParameter">
    <eOperations name="getValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        eExceptions="#//runtime/WorkflowRuntimeException">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
    </eOperations>
    <eOperations name="setValue" eExceptions="#//runtime/WorkflowRuntimeException">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      <eParameters name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" eType="#//WorkflowParameterConnection"
        eOpposite="#//WorkflowParameterConnection/targetParameters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueStrategy" lowerBound="1"
        eType="#//WorkflowParameterValueStrategy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//WorkflowParameterDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowParameterValueStrategy">
    <eOperations name="getValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        eExceptions="#//runtime/WorkflowRuntimeException">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      <eParameters name="parameter" eType="#//WorkflowParameter"/>
    </eOperations>
    <eOperations name="setValue" eExceptions="#//runtime/WorkflowRuntimeException">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      <eParameters name="parameter" eType="#//WorkflowParameter"/>
      <eParameters name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowParameterConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceParameter" lowerBound="1"
        eType="#//WorkflowParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetParameters" lowerBound="1"
        upperBound="-1" eType="#//WorkflowParameter" eOpposite="#//WorkflowParameter/connection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowParameterSimpleValueStrategy"
      eSuperTypes="#//WorkflowParameterValueStrategy">
    <eOperations name="getValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        eExceptions="#//runtime/WorkflowRuntimeException">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      <eParameters name="parameter" eType="#//WorkflowParameter"/>
    </eOperations>
    <eOperations name="setValue" eExceptions="#//runtime/WorkflowRuntimeException">
      <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      <eParameters name="parameter" eType="#//WorkflowParameter"/>
      <eParameters name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowComponentProxy" eSuperTypes="#//WorkflowComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetComponent" lowerBound="1"
        eType="#//WorkflowComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkflowParameterDirection">
    <eLiterals name="IN_OUT" literal="IN_OUT"/>
    <eLiterals name="IN" value="1" literal="IN"/>
    <eLiterals name="OUT" value="2" literal="OUT"/>
  </eClassifiers>
  <eSubpackages name="orchestration" nsURI="http://www.eclipse.org/emf/mwe/ewm/workflow/orchestration"
      nsPrefix="org.eclipse.emf.mwe.ewm.workflow.orchestration">
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowSerialOrchestrationStrategy"
        eSuperTypes="#//orchestration/WorkflowCompositeOrchestrationStrategy">
      <eOperations name="run">
        <eParameters name="composite" eType="#//WorkflowCompositeComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowCompositeOrchestrationStrategy"
        abstract="true">
      <eOperations name="run">
        <eParameters name="composite" eType="#//WorkflowCompositeComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowComponentOrchestrationStrategy">
      <eOperations name="run">
        <eParameters name="component" eType="#//WorkflowComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//orchestration/WorkflowExecutionPredicate"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="childStrategy" eType="#//orchestration/WorkflowComponentOrchestrationStrategy"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowLoopComponentOrchestrationStrategy"
        eSuperTypes="#//orchestration/WorkflowComponentOrchestrationStrategy">
      <eOperations name="run">
        <eParameters name="component" eType="#//WorkflowComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loopCondition" lowerBound="1"
          eType="#//orchestration/WorkflowExecutionPredicate" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowExecutionPredicate" abstract="true">
      <eOperations name="evaluate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="component" eType="#//WorkflowComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
      <eOperations name="reset">
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowRerunPredicate" eSuperTypes="#//orchestration/WorkflowExecutionPredicate">
      <eOperations name="evaluate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="component" eType="#//WorkflowComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowParameterPredicate" eSuperTypes="#//orchestration/WorkflowExecutionPredicate">
      <eOperations name="evaluate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="component" eType="#//WorkflowComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//WorkflowParameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowPredicateOR" eSuperTypes="#//orchestration/WorkflowExecutionPredicate">
      <eOperations name="evaluate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="component" eType="#//WorkflowComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
          upperBound="-1" eType="#//orchestration/WorkflowExecutionPredicate" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowPredicateAND" eSuperTypes="#//orchestration/WorkflowExecutionPredicate">
      <eOperations name="evaluate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="component" eType="#//WorkflowComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
          upperBound="-1" eType="#//orchestration/WorkflowExecutionPredicate" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowLoopCountPredicate" eSuperTypes="#//orchestration/WorkflowExecutionPredicate">
      <eOperations name="evaluate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="component" eType="#//WorkflowComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentCount" lowerBound="1"
          eType="#//WorkflowParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loopCount" lowerBound="1"
          eType="#//WorkflowParameter" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="runtime" nsURI="http://www.eclipse.org/emf/mwe/ewm/workflow/runtime"
      nsPrefix="org.eclipse.emf.mwe.ewm.workflow.runtime">
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowContext">
      <eOperations name="clearLog">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
      </eOperations>
      <eOperations name="initializeState"/>
      <eOperations name="getExecutionInfo" eType="#//runtime/WorkflowComponentExecutionInfo">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
      </eOperations>
      <eOperations name="getParameterValue" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
          eExceptions="#//runtime/WorkflowRuntimeException">
        <eParameters name="parameter" lowerBound="1" eType="#//WorkflowParameter"/>
      </eOperations>
      <eOperations name="getState" eType="#//runtime/state/WorkflowState">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
      </eOperations>
      <eOperations name="logError">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
        <eParameters name="message" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eOperations>
      <eOperations name="logWarning">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
        <eParameters name="message" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eOperations>
      <eOperations name="logInfo">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
        <eParameters name="message" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eOperations>
      <eOperations name="logDebug">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
        <eParameters name="message" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eOperations>
      <eOperations name="logException">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
        <eParameters name="exception" lowerBound="1" eType="#//runtime/Exception"/>
      </eOperations>
      <eOperations name="reset">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
      </eOperations>
      <eOperations name="resetState">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
      </eOperations>
      <eOperations name="resetLog">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
      </eOperations>
      <eOperations name="setExecutionInfo">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
        <eParameters name="executionInfo" lowerBound="1" eType="#//runtime/WorkflowComponentExecutionInfo"/>
      </eOperations>
      <eOperations name="setParameterValue" eExceptions="#//runtime/WorkflowRuntimeException">
        <eParameters name="parameter" lowerBound="1" eType="#//WorkflowParameter"/>
        <eParameters name="value" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </eOperations>
      <eOperations name="setState">
        <eParameters name="component" lowerBound="1" eType="#//WorkflowComponent"/>
        <eParameters name="state" lowerBound="1" eType="#//runtime/state/WorkflowState"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//runtime/WorkflowParameterMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
          eType="#//runtime/WorkflowStateMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="log" upperBound="-1"
          eType="#//runtime/WorkflowLogMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="logLevel" lowerBound="1"
          eType="#//runtime/WorkflowLogEntryType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="workflow" lowerBound="1"
          eType="#//WorkflowComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activeComponents" upperBound="-1"
          eType="#//WorkflowComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="executionInfo" upperBound="-1"
          eType="#//runtime/WorkflowComponentExecutionInfoMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentContext" eType="#//runtime/WorkflowContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowEngine" eSuperTypes="#//runtime/WorkflowRunnable">
      <eOperations name="run"/>
      <eOperations name="reset"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="workflow" lowerBound="1"
          eType="#//WorkflowComponent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          eType="#//runtime/WorkflowContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ExecutorService" instanceClassName="java.util.concurrent.ExecutorService"/>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowStateMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//WorkflowComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//runtime/state/WorkflowState" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowParameterMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//WorkflowParameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowParameterValueProxy">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowStateResolutionStrategy">
      <eOperations name="resolve" eType="#//runtime/state/WorkflowState">
        <eParameters name="workflow" eType="#//WorkflowCompositeComponent"/>
        <eParameters name="context" eType="#//runtime/WorkflowContext"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowRunnable" instanceClassName="java.lang.Runnable">
      <eOperations name="run"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowRunner" eSuperTypes="#//runtime/WorkflowRunnable">
      <eOperations name="run"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          eType="#//runtime/WorkflowContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="#//WorkflowComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowLog">
      <eOperations name="logError">
        <eParameters name="message" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eOperations>
      <eOperations name="logWarning">
        <eParameters name="message" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eOperations>
      <eOperations name="logInfo">
        <eParameters name="message" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eOperations>
      <eOperations name="logDebug">
        <eParameters name="message" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eOperations>
      <eOperations name="logException">
        <eParameters name="e" eType="#//runtime/Exception"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="entries" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="group"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="errors" upperBound="-1"
          eType="#//runtime/WorkflowLogEntry" volatile="true" transient="true" derived="true"
          containment="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="group" value="#entries"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="warnings" upperBound="-1"
          eType="#//runtime/WorkflowLogEntry" volatile="true" transient="true" derived="true"
          containment="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="group" value="#entries"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="infos" upperBound="-1"
          eType="#//runtime/WorkflowLogEntry" volatile="true" transient="true" derived="true"
          containment="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="group" value="#entries"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="debugs" upperBound="-1"
          eType="#//runtime/WorkflowLogEntry" volatile="true" transient="true" derived="true"
          containment="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="group" value="#entries"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="logLevel" eType="#//runtime/WorkflowLogEntryType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowLogEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//runtime/WorkflowLogEntryType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="#//runtime/Timestamp"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowLogMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//WorkflowComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//runtime/WorkflowLog" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="WorkflowLogEntryType">
      <eLiterals name="ERROR"/>
      <eLiterals name="WARNING" value="1"/>
      <eLiterals name="INFO" value="2"/>
      <eLiterals name="DEBUG" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="WorkflowRuntimeException" instanceClassName="org.eclipse.emf.mwe.ewm.workflow.runtime.WorkflowRuntimeException"/>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowComponentExecutionInfo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" lowerBound="1"
          eType="#//runtime/Timestamp"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" lowerBound="1"
          eType="#//runtime/Timestamp"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WorkflowComponentExecutionInfoMap"
        instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//WorkflowComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//runtime/WorkflowComponentExecutionInfo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Timestamp" instanceClassName="java.sql.Timestamp"/>
    <eSubpackages name="state" nsURI="http://www.eclipse.org/emf/mwe/ewm/workflow/runtime/state"
        nsPrefix="org.eclipse.emf.mwe.ewm.workflow.runtime.state">
      <eClassifiers xsi:type="ecore:EClass" name="WorkflowState" abstract="true">
        <eOperations name="getDisplayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" lowerBound="1"
            eType="#//runtime/Timestamp"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkflowIdleState" eSuperTypes="#//runtime/state/WorkflowState">
        <eOperations name="getDisplayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkflowRunningState" eSuperTypes="#//runtime/state/WorkflowState">
        <eOperations name="getDisplayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkflowSkippedState" eSuperTypes="#//runtime/state/WorkflowState">
        <eOperations name="getDisplayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkflowDoneState" eSuperTypes="#//runtime/state/WorkflowState">
        <eOperations name="getDisplayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkflowSuccessState" eSuperTypes="#//runtime/state/WorkflowDoneState">
        <eOperations name="getDisplayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkflowFailedState" eSuperTypes="#//runtime/state/WorkflowDoneState">
        <eOperations name="getDisplayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkflowErrorState" eSuperTypes="#//runtime/state/WorkflowDoneState">
        <eOperations name="getDisplayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
