<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mweConcept"
    nsURI="http://www.eclipse.org/xtext/common/mwe/MWEConcept" nsPrefix="mweConcept">
  <eClassifiers xsi:type="ecore:EClass" name="MWEFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Component"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Setting" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass ../../../../../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Literal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../../../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileRef" eType="#//FileRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ConfigurationElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//ConfigurationElement ../../../../../../../org.eclipse.emf.mwe.properties/src-gen/org/eclipse/emf/mwe/properties/MWEProperties.ecore#//PropertyEntry"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyFile" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileRef" eType="#//FileRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleAttribute" eSuperTypes="#//Literal #//Attribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//MWEString"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Literal #//Attribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MWEString" eSuperTypes="../../../../../../../org.eclipse.emf.mwe.properties/src-gen/org/eclipse/emf/mwe/properties/MWEProperties.ecore#//CompoundString">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MWEStringPart" eSuperTypes="../../../../../../../org.eclipse.emf.mwe.properties/src-gen/org/eclipse/emf/mwe/properties/MWEProperties.ecore#//CompoundStringPart"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaceableString" eSuperTypes="#//MWEStringPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//PropertyReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass ../../../../../../../org.eclipse.emf.mwe.properties/src-gen/org/eclipse/emf/mwe/properties/MWEProperties.ecore#//PropertyEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainString" eSuperTypes="#//MWEStringPart"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filePath" eType="#//MWEString"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeList" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanStringPart" eSuperTypes="#//MWEStringPart"/>
</ecore:EPackage>
