/**
 * <copyright>
 * </copyright>
 *
 * $Id: UnitOfWorkTestHarnessValidator.java,v 1.1 2009/05/14 04:12:27 bhunt Exp $
 */
package org.eclipse.emf.mwe.ewm.workflow.junit.validation;

import org.eclipse.emf.mwe.ewm.workflow.WorkflowParameter;
import org.eclipse.emf.mwe.ewm.workflow.runtime.state.WorkflowState;

/**
 * A sample validator interface for {@link org.eclipse.emf.mwe.ewm.workflow.junit.UnitOfWorkTestHarness}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnitOfWorkTestHarnessValidator
{
	boolean validate();

	boolean validateEndState(WorkflowState value);
	boolean validateRunningState(WorkflowState value);
	boolean validateConditionalLoopParameter(WorkflowParameter value);

	boolean validateExecutionCount(int value);
}
