/*******************************************************************************
 * Copyright (c) 2005-2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
package org.eclipse.emf.mwe.ewm.workflow.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.mwe.ewm.workflow.WorkflowParameter;

/**
 * A sample validator interface for {@link org.eclipse.emf.mwe.ewm.workflow.WorkflowParameterConnection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowParameterConnectionValidator
{
	boolean validate();

	boolean validateOutput(WorkflowParameter value);
	boolean validateInputs(EList<WorkflowParameter> value);
}
