/**
 * <copyright>
 * </copyright>
 *
 * $Id: WorkflowParameterValueStrategyValidator.java,v 1.1 2008/12/14 19:45:29 bhunt Exp $
 */
package org.eclipse.emf.mwe.ewm.workflow.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.mwe.ewm.workflow.WorkflowParameterValueStrategy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowParameterValueStrategyValidator {
	boolean validate();

}
