/**
 * <copyright>
 * </copyright>
 *
 * $Id: WorkflowComponentProxyValidator.java,v 1.1 2009/04/25 04:21:35 bhunt Exp $
 */
package org.eclipse.emf.mwe.ewm.workflow.validation;

import org.eclipse.emf.mwe.ewm.workflow.WorkflowComponent;

/**
 * A sample validator interface for {@link org.eclipse.emf.mwe.ewm.workflow.WorkflowComponentProxy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowComponentProxyValidator
{
	boolean validate();

	boolean validateTargetComponent(WorkflowComponent value);
}
