/**
 * <copyright>
 * </copyright>
 *
 * $Id: WorkflowParameterSimpleValueStrategyValidator.java,v 1.3 2009/01/12 19:01:38 pschonbac Exp $
 */
package org.eclipse.emf.mwe.ewm.workflow.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.mwe.ewm.workflow.WorkflowParameterSimpleValueStrategy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowParameterSimpleValueStrategyValidator {
	boolean validate();

}
