/**
 * <copyright>
 * </copyright>
 *
 * $Id: WorkflowLogMapValidator.java,v 1.1 2009/04/10 05:36:57 bhunt Exp $
 */
package org.eclipse.emf.mwe.ewm.workflow.runtime.validation;

import org.eclipse.emf.mwe.ewm.workflow.WorkflowComponent;
import org.eclipse.emf.mwe.ewm.workflow.runtime.WorkflowLog;

/**
 * A sample validator interface for {@link java.util.Map.Entry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowLogMapValidator
{
	boolean validate();

	boolean validateTypedKey(WorkflowComponent value);
	boolean validateTypedValue(WorkflowLog value);
}
